import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface MarkdownText {
    content: string
}

export default function TextMarkdownRenderer({ content }: MarkdownText ) {
  return (
    <div className="llm-text-container">
      <Markdown 
        remarkPlugins={[remarkGfm]}
        components={{
          // Ensure all links generated by the LLM open safely in a new tab
          a: ({ node, ...props }) => (
            <a {...props} target="_blank" rel="noopener noreferrer" className="markdown-link" />
          ),
        }}
      >
        {content}
      </Markdown>
    </div>
  );
}
