name: Deploy to OCI

on:
  push:
    branches:
      - stage-fixes-beta-experiment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Secret Presence
        run: |
          if [ -z "${{ secrets.OCI_HOST }}" ]; then
            echo "OCI_HOST is EMPTY or NOT FOUND!"
            exit 1
          else
            echo "OCI_HOST is detected."
          fi

      - name: SSH and Run Deploy Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          port: ${{ secrets.OCI_SSH_PORT }}
          script: |
            /home/ubuntu/deploy.sh